use super::processor::*;
use crate::logger::Logger;

use std::fs;

static RENDER_FLAGS_DISPLAY: &str = "
X.X..X..XX..XX..X.X...XX....................XXX.................
XXX.X.X.X.X.X.X.X.X....X...X.X.X.X.X.X........X..X.X.X.X.X.X....
X.X.XXX.XX..XX...X.....X...XX..XX..XX.......XX...XX..XX..XX.....
X.X.X.X.X...X....X....XXX..X...X...X........XXX..X...X...X......
................................................................
XXX...................X.X...................XXX.................
    .XX..X.X.X.X.X.X......XXX..X.X.X.X.X.X.X.X..XX...X.X.X.X.X.X.X.X
..X..XX..XX..XX.........X..XX..XX..XX..XX.....X..XX..XX..XX..XX.
XXX..X...X...X..........X..X...X...X...X....XX...X...X...X...X..
................................................................
XXX...................XXX...................XXX.................
X....X.X.X.X.X.X........X..X.X.X.X.X.X.X.X..XX...X.X.X.X.X.X....
XXX..XX..XX..XX.........X..XX..XX..XX..XX...X....XX..XX..XX.....
XXX..X...X...X..........X..X...X...X...X....XXX..X...X...X......
................................................................
................................................................
XXX..X..XX..XX..X.X...X.X...................XXX.................
X...X.X.X.X.X.X.X.X...XXX..X.X.X.X.X.X.X.X..XX...X.X.X.X.X.X.X.X
X...XXX.XX..XX...X......X..XX..XX..XX..XX.....X..XX..XX..XX..XX.
XXX.X.X.X.X.X.X..X......X..X...X...X...X....XX...X...X...X...X..
................................................................
XXX...................XXX...................XXX.................
X....X.X.X.X.X.X........X..X.X.X.X.X.X.X.X..XX...X.X.X.X.X.X....
XXX..XX..XX..XX.........X..XX..XX..XX..XX...X....XX..XX..XX.....
XXX..X...X...X..........X..X...X...X...X....XXX..X...X...X......
................................................................
................................................................
XXX.XXX.X.X.XXX.XX....XXX.XXX.........................X.X...XXX.
X.X..X..XXX.XX..X.X...X...XX...X.X.X.X............X.X.XXX.....X.
X.X..X..X.X.X...XX....XX..X....XX..XX.............X.X...X...XX..
XXX..X..X.X.XXX.X.X...X...XXX..X...X...............X....X.X.XXX.
................................................................
";

#[test]
fn test_execute_flags() {
    // Flags test copied from https://github.com/Timendus/chip8-test-suite?tab=readme-ov-file#flags-test
    let filepath= "./src/chip8/test_execute_flags.ch8";
    let program = fs::read(filepath).expect(format!("Failed to open file: {}", filepath).as_str());

    let logger = Logger::new(Box::new(|_| ()));
    let mut processor = Processor::new(logger);
    processor.initialize(&program);
    while !processor.run_next_instruction() {}
    let display = processor.get_display();
    let display_data: Vec<bool> = (0..display.height)
        .map(|i| (0..display.width).map(move |j| (i, j)))
        .flatten()
        .map(|(i, j)| display.get_pixel(i, j))
        .collect();

    let expected_display_data: Vec<bool> = RENDER_FLAGS_DISPLAY
        .chars()
        .filter(|c| !c.is_whitespace())
        .map(|c| c != '.')
        .collect();
    assert_eq!(expected_display_data.len(), display_data.len());
    for (expected_bit, display_bit) in expected_display_data.into_iter().zip(display_data) {
        assert_eq!(expected_bit, display_bit);
    }
}
